var annotated_dup =
[
    [ "BaseballElimination", "classBaseballElimination.html", "classBaseballElimination" ],
    [ "Board", "classBoard.html", "classBoard" ],
    [ "BoggleBoard", "classBoggleBoard.html", "classBoggleBoard" ],
    [ "BoggleGame", "classBoggleGame.html", "classBoggleGame" ],
    [ "BoggleGraph", "classBoggleGraph.html", "classBoggleGraph" ],
    [ "BoggleSolver", "classBoggleSolver.html", "classBoggleSolver" ],
    [ "BruteCollinearPoints", "classBruteCollinearPoints.html", "classBruteCollinearPoints" ],
    [ "BurrowsWheeler", "classBurrowsWheeler.html", null ],
    [ "CircularSuffixArray", "classCircularSuffixArray.html", "classCircularSuffixArray" ],
    [ "DeluxeBFS", "classDeluxeBFS.html", "classDeluxeBFS" ],
    [ "Deque", "classDeque.html", "classDeque" ],
    [ "FastCollinearPoints", "classFastCollinearPoints.html", "classFastCollinearPoints" ],
    [ "InteractivePercolationVisualizer", "classInteractivePercolationVisualizer.html", null ],
    [ "KdTree", "classKdTree.html", "classKdTree" ],
    [ "KdTreeGenerator", "classKdTreeGenerator.html", null ],
    [ "KdTreeVisualizer", "classKdTreeVisualizer.html", null ],
    [ "LineSegment", "classLineSegment.html", "classLineSegment" ],
    [ "MoveToFront", "classMoveToFront.html", null ],
    [ "NearestNeighborVisualizer", "classNearestNeighborVisualizer.html", null ],
    [ "Outcast", "classOutcast.html", "classOutcast" ],
    [ "Percolation", "classPercolation.html", "classPercolation" ],
    [ "PercolationStats", "classPercolationStats.html", "classPercolationStats" ],
    [ "PercolationVisualizer", "classPercolationVisualizer.html", null ],
    [ "Permutation", "classPermutation.html", null ],
    [ "Point", "classPoint.html", "classPoint" ],
    [ "PointSET", "classPointSET.html", "classPointSET" ],
    [ "PuzzleChecker", "classPuzzleChecker.html", null ],
    [ "RandomizedQueue", "classRandomizedQueue.html", "classRandomizedQueue" ],
    [ "RangeSearchVisualizer", "classRangeSearchVisualizer.html", null ],
    [ "SAP", "classSAP.html", "classSAP" ],
    [ "SeamCarver", "classSeamCarver.html", "classSeamCarver" ],
    [ "Solver", "classSolver.html", "classSolver" ],
    [ "TrieSet", "classTrieSet.html", "classTrieSet" ],
    [ "WordNet", "classWordNet.html", "classWordNet" ]
];